# NumPy Fundamentals for Machine Learning
**Summer of Science 2026 — CS03: Artificial Intelligence and Machine Learning**  
**Mohit Khyalia | IIT Bombay**

## Purpose

NumPy practice notebook focused on the operations that appear repeatedly in Machine Learning workflows.

Main areas:
- Array creation and manipulation
- Indexing and slicing
- Vectorization
- Matrix operations
- Broadcasting
- Shape handling
- Basic numerical computations


In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.4.1


## Creating Arrays

In [2]:
a = np.array([1, 2, 3, 4, 5])
print('1D array:', a)
print('Shape:', a.shape)   
print('dtype:', a.dtype)   
print('ndim:', a.ndim)     

1D array: [1 2 3 4 5]
Shape: (5,)
dtype: int64
ndim: 1


In [3]:
# 2D array — how a small dataset looks in NumPy
# Each row = one data point, each column = one feature
data = np.array([
    [25, 50000, 720],   # person 1: age=25, income=50k, credit_score=720
    [34, 82000, 680],   # person 2
    [45, 120000, 750],  # person 3
    [28, 45000, 630],   # person 4
], dtype=float)

print('2D array (dataset):')
print(data)
print('\nShape:', data.shape)  # (4, 3) means 4 rows, 3 columns
n_samples, n_features = data.shape
print(f'Samples: {n_samples}, Features: {n_features}')

2D array (dataset):
[[2.5e+01 5.0e+04 7.2e+02]
 [3.4e+01 8.2e+04 6.8e+02]
 [4.5e+01 1.2e+05 7.5e+02]
 [2.8e+01 4.5e+04 6.3e+02]]

Shape: (4, 3)
Samples: 4, Features: 3


In [4]:
print('zeros (3,4):')
print(np.zeros((3, 4)))       # initialise weights to zero

print('\nones (2,3):')
print(np.ones((2, 3)))        # bias initialisation

print('\narange(0, 1, 0.2):', np.arange(0, 1, 0.2))   # evenly spaced values
print('linspace(0, 1, 5):', np.linspace(0, 1, 5))     # 5 values from 0 to 1 inclusive

print('\neye(3) (identity matrix):')
print(np.eye(3))

zeros (3,4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones (2,3):
[[1. 1. 1.]
 [1. 1. 1.]]

arange(0, 1, 0.2): [0.  0.2 0.4 0.6 0.8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

eye(3) (identity matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Vectorised Operations vs Python Loops

One thing that surprised me was how large the performance difference was. I expected NumPy to be faster, but seeing the timing results made the advantage much easier to appreciate.

In [5]:
import time

n = 1_000_000
python_list = list(range(n))
numpy_array = np.arange(n, dtype=float)

# Python loop — squaring each element
start = time.time()
python_result = [x**2 for x in python_list]
python_time = time.time() - start

# NumPy vectorised
start = time.time()
numpy_result = numpy_array ** 2
numpy_time = time.time() - start

print(f'Python list comprehension : {python_time*1000:.1f} ms')
print(f'NumPy vectorised          : {numpy_time*1000:.1f} ms')
print(f'Speedup                   : ~{python_time/max(numpy_time, 1e-9):.0f}x')

# Verify results match (for the first 5 elements)
print('\nFirst 5 values match:', numpy_result[:5].tolist() == python_result[:5])

Python list comprehension : 319.4 ms
NumPy vectorised          : 7.3 ms
Speedup                   : ~44x

First 5 values match: True


**Observation**

From my understanding, vectorization is one of the biggest reasons NumPy is so widely used in Machine Learning. Operations that require explicit loops in Python can often be expressed much more efficiently using array operations.

## Indexing and Slicing

In [6]:
# Using the mini-dataset from Section 1
data = np.array([
    [25, 50000, 720, 1],   # label=1 (approved)
    [34, 82000, 680, 1],   # label=1
    [45, 120000, 750, 0],  # label=0 (rejected)
    [28, 45000, 630, 0],   # label=0
    [52, 95000, 700, 1],   # label=1
], dtype=float)

# Separate features and labels — the standard ML split
X = data[:, :-1]   # all rows, all columns except last
y = data[:, -1]    # all rows, last column only

print('Feature matrix X:')
print(X)
print('\nLabel vector y:', y)
print('X shape:', X.shape, '| y shape:', y.shape)

Feature matrix X:
[[2.5e+01 5.0e+04 7.2e+02]
 [3.4e+01 8.2e+04 6.8e+02]
 [4.5e+01 1.2e+05 7.5e+02]
 [2.8e+01 4.5e+04 6.3e+02]
 [5.2e+01 9.5e+04 7.0e+02]]

Label vector y: [1. 1. 0. 0. 1.]
X shape: (5, 3) | y shape: (5,)


**Observation:**
Initially, slicing notation looked confusing to me. After practicing with a few examples, I realized that feature selection and dataset manipulation become much easier using slicing.

In [7]:
# Boolean indexing — selecting rows that meet a condition
# This is exactly what happens when filtering data in preprocessing

# Select only approved applicants (y == 1)
approved_mask = y == 1
print('Boolean mask:', approved_mask)
print('\nApproved applicants (X rows where y=1):')
print(X[approved_mask])

# Select applicants with credit score above 700
credit_scores = X[:, 2]
high_credit_mask = credit_scores > 700
print('\nApplicants with credit score > 700:')
print(X[high_credit_mask])

Boolean mask: [ True  True False False  True]

Approved applicants (X rows where y=1):
[[2.5e+01 5.0e+04 7.2e+02]
 [3.4e+01 8.2e+04 6.8e+02]
 [5.2e+01 9.5e+04 7.0e+02]]

Applicants with credit score > 700:
[[2.5e+01 5.0e+04 7.2e+02]
 [4.5e+01 1.2e+05 7.5e+02]]


## Mathematical Operations Used in ML

In [8]:
# Dot product — the core operation in linear regression prediction
# ŷ = X @ w + b    (@ is the matrix multiply operator)

x = np.array([25.0, 50000.0, 720.0])   # one data point
w = np.array([0.002, 0.000001, 0.001]) # weights
b = -0.5                                # bias

prediction = np.dot(x, w) + b
print('Manual dot product:', np.dot(x, w))
print('Prediction (before threshold):', prediction)

# Multiple predictions at once (all 5 rows)
predictions = X @ w + b
print('\nAll predictions:', np.round(predictions, 4))

Manual dot product: 0.82
Prediction (before threshold): 0.31999999999999995

All predictions: [0.32  0.33  0.46  0.231 0.399]


**Observation:**
Before this example, matrix multiplication felt mostly mathematical. Using it to generate predictions made the connection to Machine Learning much clearer.

In [9]:
# Column-wise statistics — used in StandardScaler
# axis=0 means 'collapse across rows' → gives one value per column

print('Column means (per feature):', np.mean(X, axis=0))
print('Column stds  (per feature):', np.std(X, axis=0))
print('Column mins  (per feature):', np.min(X, axis=0))
print('Column maxs  (per feature):', np.max(X, axis=0))

# Manual standardization (what StandardScaler does)
means = np.mean(X, axis=0)
stds  = np.std(X, axis=0)
X_scaled = (X - means) / stds

print('\nScaled X (first 2 rows):')
print(np.round(X_scaled[:2], 3))

print('\nVerification — scaled column means (should be ~0):', np.round(np.mean(X_scaled, axis=0), 10))
print('Verification — scaled column stds  (should be ~1):', np.round(np.std(X_scaled, axis=0), 10))

Column means (per feature): [3.68e+01 7.84e+04 6.96e+02]
Column stds  (per feature): [1.02254584e+01 2.80756122e+04 4.02988834e+01]
Column mins  (per feature): [2.5e+01 4.5e+04 6.3e+02]
Column maxs  (per feature): [5.2e+01 1.2e+05 7.5e+02]

Scaled X (first 2 rows):
[[-1.154 -1.012  0.596]
 [-0.274  0.128 -0.397]]

Verification — scaled column means (should be ~0): [ 0. -0. -0.]
Verification — scaled column stds  (should be ~1): [1. 1. 1.]


**Observation:** Implementing StandardScaler manually using NumPy operations makes it clear that the scaler is just three lines of arithmetic — subtract the mean, divide by the standard deviation. The scaled values have mean 0 and std 1 for each feature.

In [10]:
# Mean Squared Error — the cost function for Linear Regression

y_true = np.array([1.0, 0.0, 1.0, 0.0, 1.0])
y_pred = np.array([0.9, 0.2, 0.8, 0.3, 0.7])

errors = y_pred - y_true
squared_errors = errors ** 2
mse = np.mean(squared_errors)

print('True labels   :', y_true)
print('Predictions   :', y_pred)
print('Errors        :', errors)
print('Squared errors:', squared_errors)
print('MSE           :', round(mse, 4))

# One-liner version
mse_oneliner = np.mean((y_pred - y_true) ** 2)
print('MSE (one-liner):', round(mse_oneliner, 4))

True labels   : [1. 0. 1. 0. 1.]
Predictions   : [0.9 0.2 0.8 0.3 0.7]
Errors        : [-0.1  0.2 -0.2  0.3 -0.3]
Squared errors: [0.01 0.04 0.04 0.09 0.09]
MSE           : 0.054
MSE (one-liner): 0.054


## Broadcasting

Broadcasting lets NumPy apply operations between arrays of different shapes. It is used constantly in ML — for example, subtracting the mean from every row of a matrix.

In [11]:
# Without broadcasting: you would need to reshape or loop
# With broadcasting: NumPy handles it automatically

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_vector = np.array([10, 20, 30])  # shape (3,)

# This adds row_vector to EVERY row of matrix
result = matrix + row_vector
print('Matrix:')
print(matrix)
print('\nRow vector:', row_vector)
print('\nMatrix + row_vector (broadcasting):')
print(result)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row vector: [10 20 30]

Matrix + row_vector (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


**Observation:** This is exactly what `X - means` does in the standardization step above — it subtracts the column-wise means from every row of X without needing an explicit loop.

## Random Number Generation

In [12]:
# Setting a seed ensures reproducibility
rng = np.random.default_rng(seed=42)  # modern NumPy API

# Uniform random — used for generating random train/test splits
uniform_samples = rng.uniform(low=0.0, high=1.0, size=5)
print('Uniform samples:', np.round(uniform_samples, 4))

# Normal random — used for weight initialisation in neural networks
normal_samples = rng.normal(loc=0.0, scale=0.01, size=5)
print('Normal samples (mean=0, std=0.01):', np.round(normal_samples, 6))

# Integer random — simulating class labels
random_labels = rng.integers(low=0, high=2, size=10)  # 0 or 1
print('Random binary labels:', random_labels)

# Shuffle an array without replacement
indices = np.arange(10)
rng.shuffle(indices)
print('Shuffled indices:', indices)

Uniform samples: [0.774  0.4389 0.8586 0.6974 0.0942]
Normal samples (mean=0, std=0.01): [-0.013022  0.001278 -0.003162 -0.000168 -0.00853 ]
Random binary labels: [1 0 0 1 1 1 0 1 1 0]
Shuffled indices: [6 9 1 5 4 0 8 7 3 2]


## Shapes, Reshaping, and the Dimension Rules

Shape mismatches cause more errors than almost anything else in ML code.

In [13]:
# The difference between shape (n,) and (n,1) — a frequent source of bugs

v1 = np.array([1, 2, 3])         # shape (3,)  — 1D
v2 = np.array([[1], [2], [3]])   # shape (3,1) — 2D column vector

print('v1 shape:', v1.shape)    # (3,)
print('v2 shape:', v2.shape)    # (3, 1)

# reshape to convert between them
v1_as_col = v1.reshape(-1, 1)   # -1 means 'infer this dimension'
print('v1 reshaped to column:', v1_as_col.shape)  # (3, 1)

# flatten collapses everything into a 1D array
v2_flat = v2.flatten()
print('v2 flattened:', v2_flat, '| shape:', v2_flat.shape)  # (3,)

v1 shape: (3,)
v2 shape: (3, 1)
v1 reshaped to column: (3, 1)
v2 flattened: [1 2 3] | shape: (3,)


**Observation:** Many sklearn functions require `y` to have shape `(n,)` (1D), not `(n,1)` (2D). The difference looks trivial but causes `ValueError` if not handled correctly. Using `.flatten()` or `.ravel()` before passing labels to sklearn prevents this.

## Putting It Together: Manual MSE Gradient

This section implements the gradient of MSE manually using only NumPy — the same computation that happens inside the `fit` method of the from-scratch Linear Regression notebook in Week 4.

In [14]:
# X: (m, n) feature matrix, y: (m,) labels, w: (n,) weights, b: scalar
# Gradient of MSE cost w.r.t. w and b

np.random.seed(0)
m, n = 5, 3   # 5 samples, 3 features

X_demo = np.random.randn(m, n)
y_demo = np.array([1.0, 0.0, 1.0, 0.0, 1.0])
w_demo = np.zeros(n)
b_demo = 0.0

# Forward pass
y_hat = X_demo @ w_demo + b_demo   # shape (m,)

# Gradients
errors = y_hat - y_demo            # shape (m,)
dw = (2/m) * (X_demo.T @ errors)  # shape (n,)
db = (2/m) * np.sum(errors)        # scalar

print('y_hat (predictions at init):', np.round(y_hat, 4))
print('Errors                      :', np.round(errors, 4))
print('Gradient dw                 :', np.round(dw, 4))
print('Gradient db                 :', round(db, 4))

# One gradient step with learning rate 0.1
lr = 0.1
w_updated = w_demo - lr * dw
b_updated = b_demo - lr * db

print('\nAfter one gradient step:')
print('w:', np.round(w_updated, 4))
print('b:', round(b_updated, 4))

y_hat (predictions at init): [0. 0. 0. 0. 0.]
Errors                      : [-1.  0. -1.  0. -1.]
Gradient dw                 : [-1.3901 -0.1482 -0.5278]
Gradient db                 : -1.2

After one gradient step:
w: [0.139  0.0148 0.0528]
b: 0.12


**Observation:** Every step here — matrix multiplication, element-wise subtraction, summing along an axis — uses NumPy operations covered in Sections 1–6 above.

## Quick Revision Notes

| Topic | What I should remember |
|---------|------------------------|
| Arrays | Check shape, dtype, ndim |
| Vectorization | Prefer array operations over loops |
| Slicing | `X[:, :-1]` = features, `X[:, -1]` = labels |
| Dot Product | Core operation behind many ML models |
| Scaling | `(X - mean) / std` |
| Broadcasting | Allows operations on different shapes |
| Shapes | `(n,)` and `(n,1)` are not the same |
| Gradient Computation | Mostly matrix operations and reductions |

### Things to Revisit

- Broadcasting rules
- Shape mismatch debugging
- Matrix multiplication dimensions
- Gradient derivations