# Matrix Operations
**Summer of Science 2026 — CS03: Artificial Intelligence and Machine Learning**  
**Mohit Khyalia | IIT Bombay**

---

## Project Overview

Matrices, transpose, multiplication, broadcasting, rank, determinant, and inverse using NumPy.

### Main goals:

- Implement matrix addition, transpose, and multiplication.
- Connect matrix multiplication back to the dot product.
- Use broadcasting to apply an operation across every row of a matrix.
- Compute rank, determinant, and inverse, and check when inverse exists.

---

## Setup and Imports

In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

## Creating Matrices

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print('A shape:', A.shape)
print('B shape:', B.shape)

A shape: (2, 3)
B shape: (3, 2)


## Addition and Transpose

In [3]:
C = np.array([[1, 1, 1], [1, 1, 1]])
print('A + C:\n', A + C)

print('\nA:\n', A)
print('\nA.T:\n', A.T)
print('\nA.T shape:', A.T.shape)

A + C:
 [[2 3 4]
 [5 6 7]]

A:
 [[1 2 3]
 [4 5 6]]

A.T:
 [[1 4]
 [2 5]
 [3 6]]

A.T shape: (3, 2)


## Matrix Multiplication

In [4]:
result = A @ B
print('A (2x3) @ B (3x2) =\n', result)
print('result shape:', result.shape)

A (2x3) @ B (3x2) =
 [[ 58  64]
 [139 154]]
result shape: (2, 2)


In [5]:
manual_entry_00 = np.dot(A[0, :], B[:, 0])
print('Manual A[0,:] . B[:,0]:', manual_entry_00)
print('result[0,0]:', result[0, 0])

Manual A[0,:] . B[:,0]: 58
result[0,0]: 58


**Observation:**
Each entry of `A @ B` is a dot product between a row of `A` and a column of `B` — matrix multiplication is the dot product applied across every row/column pair at once.

In [6]:
try:
    B @ A.T
    print('B @ A.T worked, shape:', (B @ A.T).shape)
except ValueError as e:
    print('Error:', e)

try:
    A @ A
except ValueError as e:
    print('A @ A error:', e)

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
A @ A error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


**Observation:**
Inner dimensions must match — `(2,3) @ (3,2)` works, `(2,3) @ (2,3)` does not. Easy to forget which side needs transposing.

## Broadcasting

In [7]:
data = np.array([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.]])

row_vector = np.array([10, 100, 1000])

print('data + row_vector:\n', data + row_vector)

data + row_vector:
 [[  11.  102. 1003.]
 [  14.  105. 1006.]
 [  17.  108. 1009.]]


In [8]:
col_means = data.mean(axis=0)
print('Column means:', col_means)

centered = data - col_means
print('\ndata - col_means:\n', centered)
print('\nNew column means (should be ~0):', centered.mean(axis=0))

Column means: [4. 5. 6.]

data - col_means:
 [[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]

New column means (should be ~0): [0. 0. 0.]


**Observation:**
`data - col_means` subtracts a (3,) vector from every row of a (3,3) matrix without a loop. This is the exact mechanism `StandardScaler` uses to centre every column.

## Rank

In [9]:
full_rank = np.array([[1, 0], [0, 1]])
dependent_rows = np.array([[1, 2], [2, 4]])

print('rank of identity-like matrix:', np.linalg.matrix_rank(full_rank))
print('rank of [[1,2],[2,4]]:', np.linalg.matrix_rank(dependent_rows))

rank of identity-like matrix: 2
rank of [[1,2],[2,4]]: 1


**Observation:**
Second row of `dependent_rows` is just 2x the first row — no new information, so rank is 1 instead of 2.

## Determinant

In [10]:
square = np.array([[4, 2], [1, 3]])
print('det(square):', np.linalg.det(square))
print('det(dependent_rows):', np.linalg.det(dependent_rows.astype(float)))

det(square): 10.000000000000002
det(dependent_rows): 0.0


**Observation:**
`dependent_rows` has determinant 0, matching its rank deficiency — a square matrix has rank less than its size exactly when its determinant is 0.

## Inverse

In [11]:
square_inv = np.linalg.inv(square)
print('inverse of square:\n', square_inv)
print('\nsquare @ inverse (should be identity):\n', square @ square_inv)

inverse of square:
 [[ 0.3 -0.2]
 [-0.1  0.4]]

square @ inverse (should be identity):
 [[ 1.  0.]
 [-0.  1.]]


In [12]:
try:
    np.linalg.inv(dependent_rows.astype(float))
except np.linalg.LinAlgError as e:
    print('Error:', e)

Error: Singular matrix


**Observation:**
A matrix with determinant 0 has no inverse — `dependent_rows` fails. This is the same matrix used in the Normal Equation for Linear Regression (`(X.T @ X)^-1`), so duplicate or near-duplicate columns in `X` cause that computation to fail or become unstable.